# Common rules for cloudbsd-nvidia-drm-*-kmod ports
# (parallel to stock nvidia-drm-kmod/Makefile.common; depends on CloudBSD DRM core)

MAINTAINER=	ports@cloudbsd.org
COMMENT=	CloudBSD NVIDIA DRM kernel module
WWW=		https://www.nvidia.com/object/unix.html
MASTER_SITES=	NVIDIA/XFree86/FreeBSD-${ARCH_SUFX}/${NVIDIA_DISTVERSION}:nvidia \
		https://codeload.github.com/freebsd/drm-kmod/tar.gz/${DRM_KMOD_GH_TAGNAME}?dummy=/:drm
DISTVERSION?=	${NVIDIA_DISTVERSION}
PORTREVISION?=	0
DISTFILES=	NVIDIA-FreeBSD-${ARCH_SUFX}-${NVIDIA_DISTVERSION}${EXTRACT_SUFX}:nvidia \
		freebsd-drm-kmod-${DRM_KMOD_GH_TAGNAME}_GH0.tar.gz:drm

.ifdef PKGNAMESUFFIX
DISTINFO_FILE=	${.CURDIR}/distinfo
.endif

ONLY_FOR_ARCHS=	amd64
USES=		kmod uidfix tar:xz

SUB_FILES=	20-nvidia-drm-outputclass.conf

# Proprietary nvidia.ko stays stock; DRM core is the CloudBSD split core.
RUN_DEPENDS+=	${KMODDIR}/nvidia.ko:x11/nvidia-kmod${PKGNAMESUFFIX}

.include "${.CURDIR}/../../x11/nvidia-driver/Makefile.version"
.include "${.CURDIR}/../../x11/nvidia-driver/Makefile.common"

LICENSE_FILE=	${WRKSRC}/../../doc/license.txt

PLIST_FILES=	${KMODDIR}/nvidia-drm.ko \
		share/X11/xorg.conf.d/20-nvidia-drm-outputclass.conf

MAKE_ENV+=	DEBUG_FLAGS=${DEBUG_FLAGS} \
		DRMKMODDIR=${WRKDIR}/drm-kmod-${DRM_KMOD_GH_TAGNAME}/
WRKSRC=		${WRKDIR}/NVIDIA-FreeBSD-${ARCH_SUFX}-${NVIDIA_DISTVERSION}/
WRKSRC_SUBDIR=	src/nvidia-drm/

.if (${NVVERSION} < 580.17302 || ${NVVERSION} >= 590.00000 && ${NVVERSION} < 595.07105) && empty(.CURDIR:M*cloudbsd-nvidia-drm-5*)
EXTRA_PATCHES+=	${FILESDIR}/extra-patch-nvidia-drm-freebsd-lkpi.c-20250918-01
.endif

.if ${NVVERSION} < 565.00000
EXTRA_PATCHES+=	${FILESDIR}/extra-patch-nvidia-drm-conftest.h
.endif

.if ${NVVERSION} < 555.04202
EXTRA_PATCHES+=	${FILESDIR}/extra-patch-nvidia-drm-freebsd-lkpi.c
.endif

post-install:
	${MKDIR} ${STAGEDIR}${PREFIX}/share/X11/xorg.conf.d/
	${INSTALL_DATA} ${WRKDIR}/20-nvidia-drm-outputclass.conf \
		${STAGEDIR}${PREFIX}/share/X11/xorg.conf.d/

post-patch:
	${REINPLACE_CMD} -e '/DRMKMODDIR.*\/linuxkpi\/dummy\/include/d' \
		${WRKSRC}/Makefile
.if ${NVVERSION} >= 570.00000
	${REINPLACE_CMD} -e 's:\&nv_drm_fbdev_module_param\,  1\,:\&nv_drm_fbdev_module_param\,  0\,:' \
		${WRKSRC}/nvidia-drm-freebsd-lkpi.c
	${REINPLACE_CMD} -e 's:bool nv_drm_fbdev_module_param = true;:bool nv_drm_fbdev_module_param = false;:' \
		${WRKSRC}/nvidia-drm-os-interface.c
.endif
.if ${NVVERSION} >= 575.00000
	${REINPLACE_CMD} -e 's:struct nv_drm_mst_display_info \*l_info = (struct nv_drm_mst_display_info:const struct nv_drm_mst_display_info \*l_info = (const struct nv_drm_mst_display_info:' \
		${WRKSRC}/nvidia-drm-drv.c
	${REINPLACE_CMD} -e 's:struct nv_drm_mst_display_info \*r_info = (struct nv_drm_mst_display_info:const struct nv_drm_mst_display_info \*r_info = (const struct nv_drm_mst_display_info:' \
		${WRKSRC}/nvidia-drm-drv.c
.endif
	linenum=$$(${SED} -ne '/^#if __FreeBSD_version/ { = ; q ; }' \
			${WRKSRC}/../nvidia/nv-freebsd.h) ; ${REINPLACE_CMD} \
			-e "$$linenum,+2d" ${WRKSRC}/../nvidia/nv-freebsd.h
	${REINPLACE_CMD} -e 's/.*pm_vt_switch_required(dev->dev, true);.*/#if __FreeBSD_version >= 1403507 \&\& __FreeBSD_version < 1500000 || __FreeBSD_version >= 1500504\n&\n#endif/' \
		${WRKSRC}/nvidia-drm-drv.c
