#!/bin/sh
# refresh-pins.sh — update VERSIONS + Makefile.inc SHAs from local ~/git clones
# or freshly fetched origin master/main.
#
# Usage:
#   GIT_ROOT=~/git ./revytech/wayfire/scripts/refresh-pins.sh
#   ./revytech/wayfire/scripts/refresh-pins.sh --fetch

set -eu
ROOT="$(CDPATH= cd -- "$(dirname "$0")/../../.." && pwd)"
GIT_ROOT="${GIT_ROOT:-$HOME/git}"
FETCH=0
[ "${1:-}" = "--fetch" ] && FETCH=1

sha() {
	repo="$1"
	branch="$2"
	path="$GIT_ROOT/$repo"
	if [ ! -d "$path/.git" ]; then
		echo "error: missing $path" >&2
		exit 1
	fi
	if [ "$FETCH" -eq 1 ]; then
		git -C "$path" fetch origin "$branch" >/dev/null 2>&1 || true
	fi
	git -C "$path" rev-parse "origin/$branch"
}

WF_CONFIG=$(sha wf-config master)
WAYFIRE=$(sha wayfire master)
PLUGINS=$(sha wayfire-plugins-extra master)
WCM=$(sha wcm master)
WFSHELL=$(sha wf-shell master)
WFJSON=$(sha wf-json main)
WFOSK=$(sha wf-osk master)
DATE=$(date +%Y%m%d)

VERSIONS="$ROOT/revytech/wayfire/VERSIONS"
INC="$ROOT/revytech/wayfire/Makefile.inc"

cat >"$VERSIONS" <<EOF
# REVYTECH Wayfire stack — pinned to revytechinc origin master/main tips
# Generated by scripts/refresh-pins.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Policy: latest product code lives on master/main (not release tags).

GH_ACCOUNT=revytechinc

revytech-wf-config       master   $WF_CONFIG
revytech-wayfire         master   $WAYFIRE
revytech-wayfire-plugins-extra  master  $PLUGINS
revytech-wcm             master   $WCM
revytech-wf-shell        master   $WFSHELL
revytech-wf-json         main     $WFJSON
revytech-wf-osk          master   $WFOSK

MESON_WAYFIRE=0.11.0
MESON_WF_CONFIG=0.11.0
MESON_WF_SHELL=0.11.0
EOF

# Patch Makefile.inc pins
tmp=$(mktemp)
sed \
	-e "s|^REVYTECH_DISTVERSION?=.*|REVYTECH_DISTVERSION?=	0.11.0.r${DATE}|" \
	-e "s|^REVYTECH_SHA_WF_CONFIG?=.*|REVYTECH_SHA_WF_CONFIG?=	${WF_CONFIG}|" \
	-e "s|^REVYTECH_SHA_WAYFIRE?=.*|REVYTECH_SHA_WAYFIRE?=		${WAYFIRE}|" \
	-e "s|^REVYTECH_SHA_PLUGINS?=.*|REVYTECH_SHA_PLUGINS?=		${PLUGINS}|" \
	-e "s|^REVYTECH_SHA_WCM?=.*|REVYTECH_SHA_WCM?=		${WCM}|" \
	-e "s|^REVYTECH_SHA_WF_SHELL?=.*|REVYTECH_SHA_WF_SHELL?=		${WFSHELL}|" \
	-e "s|^REVYTECH_SHA_WF_OSK?=.*|REVYTECH_SHA_WF_OSK?=		${WFOSK}|" \
	-e "s|^REVYTECH_SHA_WF_JSON?=.*|REVYTECH_SHA_WF_JSON?=		${WFJSON}|" \
	"$INC" >"$tmp"
mv "$tmp" "$INC"

echo "Updated pins:"
echo "  wf-config  $WF_CONFIG"
echo "  wayfire    $WAYFIRE"
echo "  plugins    $PLUGINS"
echo "  wcm        $WCM"
echo "  wf-shell   $WFSHELL"
echo "  wf-json    $WFJSON"
echo "  wf-osk     $WFOSK"
echo "Now run:  ./revytech/wayfire/install.sh --makesum"
