NVIDIA_DISTVERSION?=	610.43.02
# Explicitly set PORTREVISION as it can be overridden by the master port
PORTREVISION=	2
MASTERDIR=	${.CURDIR}/../cloudbsd-nvidia-drm-66-kmod
PKGNAMESUFFIX=	-devel

.include "${MASTERDIR}/Makefile"
